# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

create_project -in_memory -part xc7a50tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Projects/16-Bit-Processor/RISC_16_Bit/RISC_16_Bit.cache/wt [current_project]
set_property parent.project_path D:/Projects/16-Bit-Processor/RISC_16_Bit/RISC_16_Bit.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/Projects/16-Bit-Processor/RISC_16_Bit/RISC_16_Bit.srcs/sources_1/new/program_mem.v
  D:/Projects/16-Bit-Processor/RISC_16_Bit/RISC_16_Bit.srcs/sources_1/new/reg_file.v
  D:/Projects/16-Bit-Processor/RISC_16_Bit/RISC_16_Bit.srcs/sources_1/new/program_counter.v
  D:/Projects/16-Bit-Processor/RISC_16_Bit/RISC_16_Bit.srcs/sources_1/new/inst_fetch.v
  D:/Projects/16-Bit-Processor/RISC_16_Bit/RISC_16_Bit.srcs/sources_1/new/inst_decoder.v
  D:/Projects/16-Bit-Processor/RISC_16_Bit/RISC_16_Bit.srcs/sources_1/new/branch_control.v
  D:/Projects/16-Bit-Processor/RISC_16_Bit/RISC_16_Bit.srcs/sources_1/new/alu.v
  D:/Projects/16-Bit-Processor/RISC_16_Bit/RISC_16_Bit.srcs/sources_1/new/ctrl_unit.v
  D:/Projects/16-Bit-Processor/RISC_16_Bit/RISC_16_Bit.srcs/sources_1/new/mcu_top_new.v
}
catch { write_hwdef -file mcu_top.hwdef }
synth_design -top mcu_top -part xc7a50tcpg236-1
write_checkpoint -noxdef mcu_top.dcp
catch { report_utilization -file mcu_top_utilization_synth.rpt -pb mcu_top_utilization_synth.pb }
